//! Build script: rasterizes battery icon SVGs from `assets/icons/` into
//! static ARGB32 pixel arrays embedded in the binary.
//!
//! For sizes <= 22 px, 2× supersampling is applied: each icon is rendered
//! at double resolution and box-filtered back down. This preserves fine
//! detail (e.g. the charging lightning bolt) that would otherwise alias
//! away at small sizes.

use std::fmt::Write as FmtWrite;
use std::path::{Path, PathBuf};

/// Sizes to rasterize. 48 px is added for HiDPI panels; binary cost ~400 KB.
const SIZES: &[u32] = &[16, 22, 32, 48];

const LEVELS: &[u8] = &[
    0, 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90, 95, 100,
];

fn main() {
    let manifest_dir = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").unwrap());
    let icons_dir = manifest_dir.join("assets").join("icons");
    let out_dir = PathBuf::from(std::env::var("OUT_DIR").unwrap());

    println!("cargo:rerun-if-changed=assets/icons");

    let mut out = String::from(
        "// @generated by build.rs\n\n\
         pub struct EmbeddedIcon {\n\
             pub width: i32,\n\
             pub height: i32,\n\
             pub argb32: &'static [u8],\n\
         }\n\n",
    );

    for &charging in &[false, true] {
        for &level in LEVELS {
            let stem = if charging {
                format!("battery_charging_{}", level)
            } else {
                format!("battery_{}", level)
            };
            let const_base = stem.to_uppercase();
            let tree = load_svg(&icons_dir.join(format!("{stem}.svg")));
            for &size in SIZES {
                emit_icon(
                    &mut out,
                    &out_dir,
                    &format!("{const_base}_{size}"),
                    &tree,
                    size,
                );
            }
        }
    }

    let tree = load_svg(&icons_dir.join("placeholder.svg"));
    for &size in SIZES {
        emit_icon(
            &mut out,
            &out_dir,
            &format!("PLACEHOLDER_{size}"),
            &tree,
            size,
        );
    }

    // Lookup function, level snapped to nearest 5%.
    writeln!(
        out,
        "pub fn get_icon(level: u8, charging: bool, size: u32) -> &'static EmbeddedIcon {{"
    )
    .unwrap();
    writeln!(
        out,
        "    let snapped = (((level as u16 + 2) / 5) * 5).min(100) as u8;"
    )
    .unwrap();
    writeln!(out, "    match (snapped, charging, size) {{").unwrap();

    for &charging in &[false, true] {
        for &level in LEVELS {
            let cb = if charging {
                format!("BATTERY_CHARGING_{}", level)
            } else {
                format!("BATTERY_{}", level)
            };
            writeln!(out, "        ({}, {}, 16) => &{}_16,", level, charging, cb).unwrap();
            writeln!(out, "        ({}, {}, 22) => &{}_22,", level, charging, cb).unwrap();
            writeln!(out, "        ({}, {}, 32) => &{}_32,", level, charging, cb).unwrap();
            writeln!(out, "        ({}, {}, _)  => &{}_48,", level, charging, cb).unwrap();
        }
    }

    writeln!(out, "        _ => &BATTERY_0_32,").unwrap();
    writeln!(out, "    }}").unwrap();
    writeln!(out, "}}").unwrap();

    // Placeholder lookup, mirrors get_icon's size-fallback behaviour.
    writeln!(
        out,
        "\npub fn get_placeholder(size: u32) -> &'static EmbeddedIcon {{"
    )
    .unwrap();
    writeln!(out, "    match size {{").unwrap();
    writeln!(out, "        16 => &PLACEHOLDER_16,").unwrap();
    writeln!(out, "        22 => &PLACEHOLDER_22,").unwrap();
    writeln!(out, "        32 => &PLACEHOLDER_32,").unwrap();
    writeln!(out, "        _  => &PLACEHOLDER_48,").unwrap();
    writeln!(out, "    }}").unwrap();
    writeln!(out, "}}").unwrap();

    std::fs::write(out_dir.join("icons_generated.rs"), out)
        .expect("build.rs: failed to write icons_generated.rs");
}

fn load_svg(path: &Path) -> resvg::usvg::Tree {
    let data = std::fs::read(path)
        .unwrap_or_else(|e| panic!("build.rs: failed to read {}: {}", path.display(), e));
    resvg::usvg::Tree::from_data(&data, &resvg::usvg::Options::default())
        .unwrap_or_else(|e| panic!("build.rs: failed to parse {}: {}", path.display(), e))
}

fn emit_icon(out: &mut String, out_dir: &Path, name: &str, tree: &resvg::usvg::Tree, size: u32) {
    let file = format!("{name}.argb");
    std::fs::write(out_dir.join(&file), rasterize(tree, size))
        .unwrap_or_else(|e| panic!("build.rs: failed to write {file}: {e}"));
    writeln!(
        out,
        "pub static {name}: EmbeddedIcon = EmbeddedIcon {{\n\
         \x20   width: {size},\n\
         \x20   height: {size},\n\
         \x20   argb32: include_bytes!(concat!(env!(\"OUT_DIR\"), \"/{file}\")),\n\
         }};\n"
    )
    .unwrap();
}

/// Render an SVG to a pixel array at `target_size`.
/// For target_size <= 22: renders at 2× and box-filters back down.
/// For target_size > 22: renders directly at target_size.
fn rasterize(tree: &resvg::usvg::Tree, target_size: u32) -> Vec<u8> {
    let supersample: u32 = if target_size <= 22 { 2 } else { 1 };
    let render_size = target_size * supersample;

    let sx = render_size as f32 / tree.size().width();
    let sy = render_size as f32 / tree.size().height();
    let transform = resvg::tiny_skia::Transform::from_scale(sx, sy);

    let mut pixmap = resvg::tiny_skia::Pixmap::new(render_size, render_size)
        .expect("build.rs: failed to create pixmap");
    resvg::render(tree, transform, &mut pixmap.as_mut());

    if supersample == 1 {
        premul_rgba_to_argb32(pixmap.data())
    } else {
        // Downsample while still in premultiplied RGBA, averaging premultiplied
        // values is mathematically correct. Un-premultiplying first would give
        // wrong results at semi-transparent edges.
        let down = downsample_2x(pixmap.data(), render_size);
        premul_rgba_to_argb32(&down)
    }
}

/// 2× box-filter downsample. Each output pixel is the average of the
/// corresponding 2×2 block in the source. Input is premultiplied RGBA.
fn downsample_2x(src: &[u8], src_size: u32) -> Vec<u8> {
    let dst_size = src_size / 2;
    let src_stride = src_size as usize * 4;
    let mut dst = vec![0u8; (dst_size * dst_size * 4) as usize];

    for dy in 0..dst_size as usize {
        for dx in 0..dst_size as usize {
            let mut sum = [0u32; 4];
            for oy in 0..2usize {
                for ox in 0..2usize {
                    let base = (dy * 2 + oy) * src_stride + (dx * 2 + ox) * 4;
                    for c in 0..4 {
                        sum[c] += src[base + c] as u32;
                    }
                }
            }
            let out = (dy * dst_size as usize + dx) * 4;
            for c in 0..4 {
                dst[out + c] = (sum[c] / 4) as u8;
            }
        }
    }
    dst
}

/// Convert tiny-skia premultiplied RGBA -> ARGB32 network byte order.
fn premul_rgba_to_argb32(data: &[u8]) -> Vec<u8> {
    let mut out = Vec::with_capacity(data.len());
    for px in data.chunks_exact(4) {
        let (r_pm, g_pm, b_pm, a) = (px[0], px[1], px[2], px[3]);
        let (r, g, b) = if a == 0 {
            (0, 0, 0)
        } else {
            let a32 = a as u32;
            (
                ((r_pm as u32 * 255 + a32 / 2) / a32) as u8,
                ((g_pm as u32 * 255 + a32 / 2) / a32) as u8,
                ((b_pm as u32 * 255 + a32 / 2) / a32) as u8,
            )
        };
        out.extend_from_slice(&[a, r, g, b]);
    }
    out
}
